CREATE TABLE "Files" (
	"FileId"	INTEGER NOT NULL,
	"FileName"	TEXT NOT NULL,
	"FileInfo"	TEXT,
	"Extension"	TEXT NOT NULL,
	"Market"	TEXT,
	"OriginalName"	TEXT NOT NULL,
	"PeriodYears"	INTEGER,
	"CreatedAt"	TEXT NOT NULL,
	PRIMARY KEY("FileId" AUTOINCREMENT)
);

CREATE TABLE "Market_Data" (
	"Id"	INTEGER NOT NULL,
	"FileId"	INTEGER NOT NULL,
	"Date"	TEXT NOT NULL,
	"Price"	REAL NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT),
	FOREIGN KEY("FileId") REFERENCES Files
);